### ISSUE TITLE
Checkbox hovered state handling is missing in appearance.

### ISSUE THREAD

**Issue by level420** [johnspackman/aristo#1]
Hi John!

I'm currently updating my theme, which is based on your aristo theme, to work with current master of aristo.

One thing I've observed is the missing "hovered" state handling for the checkbox. Is this by intention? 

I've seen you have moved the corresponding images to resource/aristo/decoration/form/old and removed the _-hover-_ related code from the checkbox appearance.

This happened in commit https://github.com/johnspackman/aristo/commit/4319128ab788e6b59502acb6ca839c84a60320b3 

On the other side hover appearance is still active for radiobuttons.

Regards
Dietrich

**Comment by johnspackman** [comment]
Hi Deitrich

I’m not 100% sure now but at the time I had to redo the images for the checkboxes because I was clearing up some inconsistencies in the implementation, but in the PSD only the basic on/off/disabled variants existed so I had to create all variants before cutting out new resources.  Looking at the PSD I can see the new checkbox icons in there, and I suspect that I was struggling to differentiate between focused, hovered & focused+hovered.  

If that’s what it was then in hindsight I’m surprised I just deleted the hovered style entirely (e.g. rather than just using the same image as used by focused or something) but maybe it’s one of those moments…

If you want to do a  pull request and get a hovered state back in I'll bring it back in?

Regards
John

**Comment by level420** [comment]
Hi John

I've already extracted those missing combinations and created a few more in the Aristo-24.psd file, including those for *-hovered-invalid, *-focused-invalid, *-focused-hovered-invalid.

But I've made another modification, which gives the _-invalid-_ checkbox a red border of 1px in contrary to the 2px as it was before. The 2px was too dominant in my opinion.

I think I'll prepare a pull request early next, including the modified Aristo-24.psd file.

Would this be OK?

**Comment by level420** [comment]
If you like I'll send you the modified psd file as a pm.

**Comment by johnspackman** [comment]
yep, that's fine just include it all in the one pull request - how recent was the PSD before you modified it (eg was it what was already in master?)

**Comment by level420** [comment]
I've cloned the PSD yesterday from master.

**Comment by johnspackman** [comment]
perfect

**Comment by level420** [comment]
While going forward to define all possible state combinations for radio buttons and check boxes, I've realized that there exists a "pressed" state for radio buttons, but not for check boxes.

I've checked native radio buttons on Chrome, Firefox and IE on Windows 7. Firefox and IE have a visual representation for the "pressed" state, Chrome does not.

Should I create "pressed" state icons as well?

This would mean to have icons for state combinations like pressed-checked-hovered-focused-invalid etc.

What do you think?

**Comment by level420** [comment]
Here we go:

https://github.com/johnspackman/aristo/pull/3

**Comment by johnspackman** [comment]
done
